### ISSUE TITLE
Newer versions of koGrid causes JQuery error in IE8

### ISSUE THREAD

**Issue by donpedro** [Knockout-Contrib/KoGrid#101]
Using old KoGrid code works fine, but newer versions fail in IE8 with the following error:

SCRIPT65535: Unexpected call to method or property access. 
jquery-1.7.1.js, line 5763 character 5

Working, with old koGrid 1.x:  http://jsfiddle.net/abrev8ed/FhGpp/7/

IE8 fail, with koGrid 1.2.2: http://jsfiddle.net/abrev8ed/FhGpp/

**Comment by orneryd** [comment]
this should be fixed in 1.2.4
