### ISSUE TITLE
IE8 cannot render the grid

### ISSUE THREAD

**Issue by arjendeblok** [Knockout-Contrib/KoGrid#103]
Issue 101 still exists even in 1.3.0.
IE 8 has problems with the following code in kg.utils:

```
   var template = document.createElement('script');
    $(template).attr('type', 'text/html');
    $(template).attr('id', templId);
    $(template).html(templText);
```

It seems that IE 8 does not allow to set an InnerHTML in a script element, which is what the last statement does.

**Comment by orneryd** [comment]
fixed in aggregates branch and will be merged into main
