### ISSUE TITLE
headerCellTemplate should be allowed in columnDefs

### ISSUE THREAD

**Issue by lhope** [Knockout-Contrib/KoGrid#109]
Currently the headerCellTemplate option is only available to be set in the options to KoGrid. It would be useful if it could be set per-column in the columnDefs, just like the cellTemplate.

This means that additional functionality such as selectable columns could be used on a per-column basis.

**Comment by orneryd** [comment]
it is allowed in column defs. there is a headerTemplate option for the grid and a headerCellTemplate option in the column definition. I have updated the documentation. https://github.com/ericmbarnard/KoGrid/wiki/Defining-Columns

**Comment by lhope** [comment]
Two things:
1. From inspecting the source, you set the option using 'headerCellTemplate' as a property to the object passed to KoGrid, or you use the 'headerTemplate' property in the column defs. That makes sense, but the updated documentation in the wiki says 'headerCellTemplate' for this. I would just edit it myself except for:
2. Setting the header template using the column defs doesn't seem to work. If I use headerCellTemplate in the coldefs, then that property is just ignored (as I'd expect). If I use headerTemplate, then I get a blank header:

``` html
<div style="height: 30px; border-right-width: 0px; width: 200px;" data-bind="kgHeader: { value: '58957' }, style: { width: $parent.columns()[3].width() + 'px'}, css: { 'kgNoSort': false }" class=" kgHeaderCell col3 "></div>
```

I think the headerTemplate isn't being loaded or found. Is that a regression? If I use the same template in the toplevel option 'headerCellTemplate', it works okay.

**Comment by lhope** [comment]
I think I have resolved the issue with unfound header templates and am making a pull request to solve it now.
