### ISSUE TITLE
Use a sub grid in master/detail and load sub grid data using getJSON

### ISSUE THREAD

**Issue by jducobu** [Knockout-Contrib/KoGrid#110]
I have a master kogrid that works find. In clicking on a master kogrid's row, i want to have a detail kogrid where the data are loaded using getJSON.

**Comment by orneryd** [comment]
here is an example of doing master-details with the grid. http://ericmbarnard.github.com/KoGrid/examples/MasterDetails.html

**Comment by AaronBastian** [comment]
Any chance on getting this example back online? This links to a 404
