### ISSUE TITLE
Column grouping

### ISSUE THREAD

**Issue by ajuliao** [Knockout-Contrib/KoGrid#113]
I am trying to find an option for grouping columns but can't find it. If there isn't one, this would be a desirable feature to add.

Thanks,

AJ

**Comment by orneryd** [comment]
we are working on this at the moment. It will be implemented similar to ng-grid which is built on angular. http://timothyswt.github.com/ng-grid/examples/groupby.html

**Comment by ajuliao** [comment]
Thanks! That looks pretty cool. Does that mean you will also be implementing rearranging columns with drag and drop?

**Comment by orneryd** [comment]
Added in 2.0
