### ISSUE TITLE
Add the samples to the repository

### ISSUE THREAD

**Issue by HoosierMike** [Knockout-Contrib/KoGrid#118]
We should be able to download the .zip file and run the samples you have on your home page right out of the box. I've spent the last hour and and half trying to get the large dataset sample to run and have not gotten it to work yet. There should be a samples folder than run out of the box with all the paths set to the right folders for css and js files

Thank you

**Comment by ozkarservices** [comment]
My2ndGeneration, I was able to read my database records and load into the KOGrid. I spend about 1 days understanding the process.

The way I got it to work was by using  jQuery and Ajax Web  Services call. Let me know if you want an example of my code.

**Comment by orneryd** [comment]
more examples are coming http://angular-ui.github.com/ng-grid/
