### ISSUE TITLE
Changing column definition breaks grid

### ISSUE THREAD

**Issue by cvoijen** [Knockout-Contrib/KoGrid#119]
When applying the data binding programmatically (using ko.applyBindingsToNode) instead of declaratively in the markup, any manipulation of the column definition using the observable array breaks the grid.

The kg.cssBuilder.buildStyles function is called with a undefined input parameter and accessing the config property will throw an exception.

The issue does not occur when the bindings are applied declaratively.

I resolved the issue by changing line 54 in src / BindingHandlers / koGrid.js from
ko.applyBindings(bindingContext, element);
into
ko.applyBindingsToNode(element, { koGrid: options }, bindingContext);

Now both methods work.

**Comment by orneryd** [comment]
Fixed in 2.0
