### ISSUE TITLE
Should have an option for html values on cells(autogenerated or manual)

### ISSUE THREAD

**Issue by thelinuxlich** [Knockout-Contrib/KoGrid#12]
Use case: JSON data with html entities

**Comment by ericmbarnard** [comment]
Sorry, I didnt comment on this earlier.

Do you mean with this that your JSON objects have a property on them and that it could be valid html?

Would this not be solve-able using a custom Cell or Header template?

**Comment by orneryd** [comment]
This is solvable using a cell/row template. fix: don't use DOM entities in your JSON data, only use the values you need to display and create the entities with the cell/row template.
