### ISSUE TITLE
Does kogrid persist selected checkbox values

### ISSUE THREAD

**Issue by suryabg2000** [Knockout-Contrib/KoGrid#121]
Team,

I want to build KOGrid by taking below things into account
1. First time, KO should only  10 records
2. select couple of checkbox or select all
3. Clicking on 2nd page should show pageIndex 2 values
4. Clicking on Sort should sort & show only 10 records.

How to achieve these thing?? can any one help me in this regard.

**Comment by orneryd** [comment]
not when server-side paging because of the implementation. This is not something we can support either with the current implementation. sorting with server side paging will only sort what is being displayed unless you use external sorting
