### ISSUE TITLE
2.0 Issue - Property 'selectedItems' of object [object Object] is not a function

### ISSUE THREAD

**Issue by davidjsilva** [Knockout-Contrib/KoGrid#125]
Looking forward to using the KoGrid 2.0!!  My initial tests are coming up with a javascript error.  Here is a simple fiddle to illustrate: http://jsfiddle.net/55GKa/1/

Uncaught TypeError: Property 'selectedItems' of object [object Object] is not a function koGrid-2.0.0.debug.js:1388

Did the options change?

**Comment by orneryd** [comment]
Sorry ti looks like there was a merging issue. I just hot-fixed the issue.
