### ISSUE TITLE
2.0 Issue - No data being displayed w/ javascript errors

### ISSUE THREAD

**Issue by davidjsilva** [Knockout-Contrib/KoGrid#126]
The selectedItems issue is fixed thanks for the quick turnaround, but I'm still having issues shown in this fiddle: http://jsfiddle.net/55GKa/5/

Basically, the columns are being displayed now but with no data.

Also, if you click on the Select All checkbox you get the following error: Uncaught TypeError: Cannot read property 'nodeType' of undefined knockout-2.2.0.debug.js:2138

And, if you click on the column heading to sort or to resize the column you get the following error: Uncaught TypeError: Cannot read property 'Field1' of undefined koGrid-2.0.0.debug.js:1857

**Comment by orneryd** [comment]
Hooray! merging issues should be fixed now. http://jsfiddle.net/55GKa/5/
