### ISSUE TITLE
2.0 Issue Select All Column Issue

### ISSUE THREAD

**Issue by davidjsilva** [Knockout-Contrib/KoGrid#127]
Thanks for fixing those issues last night, I really like the enhancements you've made.  With that said, I found a couple more javascript errors which can be seen on the following fiddle: http://jsfiddle.net/55GKa/7/
1. When clicking the Select All checkbox
   Uncaught TypeError: Cannot read property 'nodeType' of undefined knockout-2.1.0.debug.js:2042
2. Scroll all the way down on the grid or until you've reached the next page and then click the Select All checkbox
   Uncaught TypeError: Cannot call method 'selected' of undefined koGrid-2.0.0.debug.js:1616

**Comment by orneryd** [comment]
This should be resolved in latest commits. Thanks for finding these issues! :)

**Comment by davidjsilva** [comment]
OK I can confirm these issues are fixed, however I noticed another issue with the Selected Items count in the footer.  You can use the same fiddle to test: http://jsfiddle.net/55GKa/7/
1. Hit Select All checkbox and Selected Items will equal 500
2. Uncheck Select All checkbox and Selected Items is still 500 instead of 0
3. Re-check Select All checkbox and Selected Items will equal 1000 and so on

**Comment by orneryd** [comment]
Should be fixed now. I swear i had fixed all these issues before the merge. I hate fixing the same problems twice. :(

**Comment by davidjsilva** [comment]
Wanted to point out that if you click anywhere on the row the Selected Item count gets updated correctly.  However, if you click the actual check box in each row it doesn't actually update the Selected Item count even though it does change the selected state of the row.  You can see it here: http://jsfiddle.net/55GKa/16/

**Comment by orneryd** [comment]
I see, I created issue 135. Thanks!
