### ISSUE TITLE
2.0 Issue - How to access root view model from row/cell level

### ISSUE THREAD

**Issue by davidjsilva** [Knockout-Contrib/KoGrid#130]
Prior to 2.0 I used to be able to access the root view model attached to the grid from within a cell template by using knockout's $root.  For some reason, with 2.0 I am no longer able to do that.  $root is now the kg.Row and $data is the kg.Column.

I have created a fiddle to illustrate what I was trying to do: http://jsfiddle.net/55GKa/10/

I have a function doSomething on my view model that I want to execute when I click a button from within a cell template.  However, since $root is now the kg.Row it can't find that method and throws a javascript error.

Please advise on why this is no longer working, or what I can do to get access to the main view model of the grid.

**Comment by orneryd** [comment]
looking into how we can do this. the documentation is a bit insane http://knockoutjs.com/documentation/custom-bindings-controlling-descendant-bindings.html 

I am sure it can be done, I just want to do it in the right way. If you have any ideas or understand the documentation there feel free to submit a pull request :)

**Comment by orneryd** [comment]
adding $userViewModel to all of the binding contexts. you should be able to access your view model from anywhere in the grid now.

**Comment by davidjsilva** [comment]
Great solution works perfectly!  Thanks.

**Comment by sanderd** [comment]
Moving this to issue #210.
There's an issue when the data source is a child-list in a parent object, and you want to access a sibling of that parent. For instance, with clickhandlers.
