### ISSUE TITLE
How do you specify a default sort for kogrid ?

### ISSUE THREAD

**Issue by ghmanas** [Knockout-Contrib/KoGrid#131]
Hello there,
I am getting the following error "Error: Unable to parse bindings. Message: SyntaxError: missing : after property id;"

when I put this in  the data-bind property:

sortInfo: {field = 'CodeId', direction='asc'}, // in the data-bind

How do I specify a default sort order that is used when the grid is loaded the first time?

Thanks,
Manas

**Comment by orneryd** [comment]
you need to specify it using proper json syntax  sortInfo: {field: 'CodeId', direction: 'asc'}

**Comment by ghmanas** [comment]
Thank you Tim,

I did that (sortInfo: {field: 'CodeId', direction: 'asc'}) but on koGrid.debug.js line #1255
this.sortInfo.subscribe(sortData);

I get the following error:
TypeError: this.sortInfo.subscribe is not a function

Problem not resolved. How do I reopen this issue, so that I can get help?

**Comment by orneryd** [comment]
closing this in favor of #138 since it is a duplicate
