### ISSUE TITLE
2.0 Issue - Cannot disable multiSelect

### ISSUE THREAD

**Issue by davidjsilva** [Knockout-Contrib/KoGrid#136]
Even if multiSelect is set to false, the grid still allows you to select multiple rows which can be seen in this fiddle: http://jsfiddle.net/55GKa/17/.

Few reasons for this maybe: multiSelect is observable but looks like some places in the code expect it to not be:
- in the self.ChangeSelection function the self.multi conditions would need to be self.multi().  self.multi would always evaluate to true
- self.multiSelect = ko.observable((self.config.canSelectRows && self.config.multiSelect)); would need to be self.multiSelect = ko.observable((self.config.canSelectRows && self.config.multiSelect()));
- in the defaultGridTemplate: css: {\'kgNoMultiSelect\': !multiSelect}.  For negating observable to evaluate correctly it would need to be !multiSelect().

**Comment by orneryd** [comment]
multiselect is not an observable option. http://jsfiddle.net/55GKa/18/

That being said, I don't think it should be and observable option. But I can see why some may want to switch between them on the fly... Is that something you need?

**Comment by davidjsilva** [comment]
OK great I actually think multiSelect not being observable is the correct behavior.  I was thrown off by line 997 multiSelect: ko.observable(true).  When I saw that I made mine observable to follow suit.  I guess just need to change that line to multiSelect: true to eliminate any confusion???

**Comment by orneryd** [comment]
Ah! I see, it is a mistake in the defaults. It works because we are evaluating true/false and since the object exists it's true. The multiSelect option is not observable and I will make sure the documentation is updated.

Thanks!
