### ISSUE TITLE
jQuery UI theme support

### ISSUE THREAD

**Issue by thelinuxlich** [Knockout-Contrib/KoGrid#14]

**Comment by HoosierMike** [comment]
I second this issue, theme-roller support would be awesome, in fact, just make it the default, if you want to change the default style over to the right css names for that then perfect, but this would be a huge benefit to us.

**Comment by orneryd** [comment]
Fixed in 2.0

**Comment by HoosierMike** [comment]
I'm confused, are you saying koGrid now supports jQuery ThemeRoller themes? And can we please beg Eric to cut a new release after merging the outstanding pull request ...

**Comment by orneryd** [comment]
Yes, it supports themeRoller themes and once I make sure that all of the little issues from the re-arch are fixed we will be cutting a new release.

**Comment by HoosierMike** [comment]
I think I see this is checked in now, so do all I have to do is include a theme roller them and it will take on those characteristics?

**Comment by orneryd** [comment]
You will want to use the configuration option jqueryUITheme: true.

**Comment by EntitySpaces** [comment]
Ya, I found that eventually, it kind of worked, but had all kinds of issues, but then I was still including the koStyle.css file or whatever that comes with koGrid. Our deadline is December 21st, I have an issue with one particular case with the wijmo grid that I was going to use koGrid for (a mailbox). But I just cannot without real samples, I'm hanging on and doing the mailbox as the last thing before we go live, I'll use koGrid if there's samples that show how on the new changes, love what you guys are doing.

Hopefully, unlike the current samples, we'll be able to download the zip and run them right out of the samples folder untouched, that's how I do my github repo's, if for nothing else that I can quickly run them when I make changes and make sure things still work, but users need real samples they run locally.

**Comment by orneryd** [comment]
There are examples of the grid that koGrid is based on that are coming online. The implementation details for the options are identical except for some values being observables and using knockout's data-bind syntax 

http://angular-ui.github.com/ng-grid/ 

Once we finish those we will just copy paste and change the few details to knockout syntax.
