### ISSUE TITLE
Issue 2.0.6: cellTemplate does not work

### ISSUE THREAD

**Issue by mp-software** [Knockout-Contrib/KoGrid#142]
I'm using a cellTemplate like this but it does not work any more. The last version where it works was :
commit aa03a95eb99b1e3297f9b2439b8926e7bd347bd2
Author: Timothy Sweet timothyswt@gmail.com
Date:   Tue Oct 16 15:51:10 2012 -0700

```
<script type="text/html" id="editCellTmpl">
    <div data-bind="kgCell: $cell">
        <input type="text" data-bind="value: $cellValue" style="width: 250" />
    </div>
</script>

<div id="GridTest" class="gridTest" style="height: 600px; max-width: 700px;" 
        data-bind="koGrid: { data: daten,
                             columnDefs: [
                                           { field: 's2projName', displayName: 'Projekt', width: 400 },
                                           { field: 'sollStunden', displayName: 'Soll Stunden', width: 250, cellTemplate: 'editCellTmpl' }
                                         ],
                             autogenerateColumns: false }">

</div>
```

Can you please provide me a solution? Greets, mp-software

**Comment by ZiadJ** [comment]
Id specific template scripts have been abandoned for being inefficient and restrictive. See https://github.com/ericmbarnard/KoGrid/issues/132 for more details.

**Comment by mp-software** [comment]
Thank's, this solves my problem!

**Comment by mp-software** [comment]
But now I've another problem, my field 'sollStunden' in my ViewModel is not updatet if I edit the cell value

**Comment by ZiadJ** [comment]
As mentioned in the cell template documentation you need to use $data.getProperty($parent) for your fields now. Also in the latest commit the root view model is now accessible through $userViewModel instead of  $root.

**Comment by mp-software** [comment]
Thanks for help, but I'm sorry, I don't know how to see the changed values in my ViewModel - here is my code:

##Edit: If you have a bunch of code, make a plunker or jsfiddle. Don't paste a crapload of code on here. ##

**Comment by ZiadJ** [comment]
Here's a simplified version of your template:

<pre>
var editCellTemplate = '&lt;input type="text" data-bind="css: \'kgCellText\', value: $data.getProperty($parent)" /&gt;';
</pre>

Let me know if you're still having trouble with it and I'll look deeper into it.

**Comment by orneryd** [comment]
I have updated the documentation to further explain how to use an input in the field

https://github.com/ericmbarnard/KoGrid/wiki/About-Custom-Templates

Basically getProperty is a convenience method to process the cellFormatter function (option in columnDefs) if present. and only returns the value of the underlying observable (if it is observable).

For two way data-binding on that you need to access it through this syntax:

``` html
<input type="text" data-bind="value: $parent.entity['myFieldName']"/>
```

the attr binding is not required, and doesn't affect the text when using an input since it is a control and not a span/div.

hope this helps.

**Comment by ZiadJ** [comment]
@timothyswt Thanks for pointing out about the two way data-binding.

**Comment by orneryd** [comment]
you can also leave it in a script tag the same way you normally did but instead of passing the string name of the template id you just need a jquery selector calling html().

``` html
<script type="text/html" id="myCellTemlateId">
  <input type="text" data-bind="value: $parent.entity['myFieldName']"/>
</script>
```

define columns:

``` javascript
columnDefs: [{ field: 's2projName', displayName: 'Projekt', width: 400 },
                          { field: 'sollStunden', displayName: 'Soll Stunden', width: 250, cellTemplate: $('#myCellTemlateId').html()}]
```

**Comment by alex-okrushko** [comment]
@timothyswt Had the same problem...
Using 'myFieldName' is a bit awkward. Template now becomes field-specific (looses the benefits of Template)

**Comment by orneryd** [comment]
You can also use $data.field in place of 'myFieldName'

It returns whatever your data model is. So if it is not an observable the two way databinding will not work.

**Comment by alex-okrushko** [comment]
@timothyswt Thanks.
I'm still getting the grasp of koGrid (and Knockout), but it looks like 2.0 has major (undocumented) changes. Was really frustrated of why my cell template was doing the ajax request instead on using the template. 

But I seem to like koGrid. I'm switching from dataTables.net.

Note: dataTables has amazing documentation. Just something to think about :)

Regards

**Comment by orneryd** [comment]
Documentation is always a struggle. We are attempting to improve it daily. If you're interested, check out http://angular-ui.github.com/ng-grid which is what the new architecture is based on. It is a work in progress but We will soon be replacing KoGrid documentation with that same format.

**Comment by alex-okrushko** [comment]
@timothyswt 
After fighting more time with trying to make `$('#MyTemplateID').html()` work I found that you test it for `var TEMPLATE_REGEXP = /^<.+>/;`
However, most of the templates  (well, actually all of them :) ) start with 'tab' or 'new line' thus koGrid will still try to the ajax page.

My suggestion will be to use `var TEMPLATE_REGEXP = /<.+>/;` - not to enforce "begins with <"

**Comment by orneryd** [comment]
I am going to open a separate issue as your're totally correct about that

**Comment by orneryd** [comment]
I also update the row and cell template libraries to help further explain the differences in the templating system from the old version to 2.0 

https://github.com/ericmbarnard/KoGrid/wiki/Row-Template-Library

https://github.com/ericmbarnard/KoGrid/wiki/Cell-Template-Library

**Comment by mp-software** [comment]
Thank you very much, ...value: $parent.entity[$data.field]...solves my problem!

**Comment by davidjsilva** [comment]
I like the use of $parent.entity[$data.field] but how would I use it if I have sub objects like the sample object below

``` javascript
{
  Field1: ko.observable(),
  Obj1: {
    ObjField1: ko.observable()
  }
}
```

In this case $parent.entity[$data.field] does not work because $data.field would be 'Obj1.ObjField1'.  I have included this fiddle to show my issue: http://jsfiddle.net/pbqHF/3/

**Comment by JByfordRew** [comment]
I keep getting 'Uncaught Error: Syntax error, unrecognized expression: <div type="text" data-bind="text:  $data.getProperty($parent)"></div>' in jquery 1.9.1 library

when use the cellTemplare : $('#mytemplateid").html()

**Comment by JasonRawlins** [comment]
I'm also getting a similar error: "Error: Syntax error, unrecognized expresion: <div>Test</div>"

columnDef:
{ field: 'Id', displayName: 'Id', width: 110, cellTemplate: $('IdTemplate').html() }

template:

<script id="IdTemplate" type="text/html">
    <div>Test</div>
</script>

Script versions:
koGrid-2.1.1.js
jquery-1.9.1.js
knockout-2.2.1.js

Chrome stack trace:
error - jquery-1.9.1.js (line 4421)
tokenize - jquery-1.9.1.js (line 5076)
select - jquery-1.9.1.js (line 5460)
Sizzle - jquery-1.9.1.js (line 3998)
find - jquery-1.9.1.js (line 5576)
....
