### ISSUE TITLE
Example pages not available

### ISSUE THREAD

**Issue by ZiadJ** [Knockout-Contrib/KoGrid#144]
The example pages referred to on the main page don't exist anymore.

**Comment by jonricaurte** [comment]
That's because I am working on a new examples page and the old examples
page was referring to kogrid before it even hit 1.0 (that page was last
updated in April). I should have the new examples page up today.

**Comment by alex-okrushko** [comment]
@xcrico Much appreciated :+1: server-side processing is a key :)

**Comment by joshua1** [comment]
Page still not available.Why is this closed
