### ISSUE TITLE
FAQ: bootstrap styling

### ISSUE THREAD

**Issue by alex-okrushko** [Knockout-Contrib/KoGrid#145]
@timothyswt I see that there is **bootstrap** as part of this project. 
Is there any way to style the koGrid with it? (off-the-shelf)
Honestly, I see no problems for it, since TB does not force to use `<table>` tags (as long as `.table` css class and other classes are used - you should be good).
Thanks

**Comment by JudahGabriel** [comment]
The header styles won't work (just checked with Bootstrap 3 RC1). But the rest seems to work well enough.

**Comment by alex-okrushko** [comment]
Apparently project is dead.
