### ISSUE TITLE
Virtual/buffered/infinite scrolling not working with deferred objects

### ISSUE THREAD

**Issue by thcgit** [Knockout-Contrib/KoGrid#146]
I have a grid where the data source is an array of deferred ko.computed objects. The way it works is:
1. I get the total count of objects on the server and create an observable array with a size of that count.
2. I fill the observable array with ko.computed objects with deferred evaluation.
3. The read function of the ko.computed objects fetches 50 records from the service and replaces the corresponding items in the observable array with the fetched records.

This used to work in the previous version of kogrid. When scrolling down the grid, the ko.computed objects are evaluated.

With KoGrid 2.0.6, at first I encountered an issue in kg.SearchProvider.evalFilter at this part:

```
var obj = {};
for (var prop in item) {
    if (item.hasOwnProperty(prop)) {
        obj[prop] = ko.utils.unwrapObservable(item[prop]);
    }
}
return JSON.stringify(obj).toLowerCase().indexOf(ft) != -1;
```

It was failing on the "**ko_proto**" property with a knockout error "pass a function that returns the value of the ko.computed".

So I changed the code to:

```
var obj = ko.utils.unwrapObservable(item);
return JSON.stringify(obj).toLowerCase().indexOf(ft) != -1;
```

That resolved the initial error. The problem now is that when I scroll down the grid, the ko.computed objects are not being evaluated. So no additional data is being retrieved after the initial load.

Is there a different way I should be implementing this behaviour in the new KoGrid?

Thanks!

**Comment by orneryd** [comment]
I updated your header since it inaccurately simplified the issue at hand. The issue is the support for deferred object.

The filtering issue is that unwrapObservable does not unwrap nested observables such as data models constructed with the mapping plugin.         

http://cloud.github.com/downloads/SteveSanderson/knockout/knockout-2.2.0.debug.js

``` javascript
unwrapObservable: function (value) {
    return ko.isObservable(value) ? value() : value;
},
```

The function I implemented to handle observables during search also only handles top level observables and not fully nested which would require walking down the tree and unwrapping as I go (adversely affecting performance the larger the tree is)

As for your issue, I will need to investigate how deferred object are handled and see where the problem lies.

**Comment by thcgit** [comment]
Tim, thanks for clarifying the filtering issue.

I understand why my deferred computed objects aren't working now. They are actually all being evaluated during evalFilter on init. So they are no longer being evaluated when scrolled into view. Due to an issue with my implementation of the computed's read function, that was causing additional data not to be loaded.

Is there a way to disable the search provider completely if it's not required?

To give you an idea of what I'm trying to do, here's a sample where I override evalFilter to do nothing and the buffered loading works: http://jsfiddle.net/Xf5T3/12/

(Ignore the skipped rows when scrolling a large area at the time. This is a simplified demo.)

I'm reconsidering whether using computed objects is the right approach to the problem. Does KoGrid have a particular supported or recommended way of doing buffered grid loading?

Will KoGrid also destroy kg.Row objects when not being shown anymore so that there won't be tens of thousands left in memory if I scroll through that many records? On the source data side, the source observable array will have a max buffer size so the oldest cached records will be purged when the buffer is full.

Thanks again.

**Comment by orneryd** [comment]
Yes, you can disable the search provider by setting filterOptions: {useExternalFilter: true}

And now there is support for items flagged _destroy see issue #134

Hope that helps
