### ISSUE TITLE
Drag / Drop Grouping support doesn't work in IE

### ISSUE THREAD

**Issue by HoosierMike** [Knockout-Contrib/KoGrid#147]
I actually got it to work once, but it's basically unusable. I can use the little drop down window to group however, so it's just a minor little drag drop issue.

**Comment by jonricaurte** [comment]
Have you tried setting  jqueryUIDraggable: true in your grid options and
referencing jQueryUI? if you haven't you can check it out in the examples:

http://ericmbarnard.github.com/KoGrid/#/examples

It's the second example under grouping.

**Comment by EntitySpaces** [comment]
Sorry, I was actually running the samples, try it in IE, you cannot drag the columns to the grouping area ...

**Comment by jonricaurte** [comment]
Oops, apparently the jQuery UI reference was missing from the plunker.
Should work now in IE.
