### ISSUE TITLE
Suggestion: Use JSFiddle rather than Plunker

### ISSUE THREAD

**Issue by EntitySpaces** [Knockout-Contrib/KoGrid#148]
JSFiddle is far superior to Plunker, not to mention that I cannot seem to get any of the plunkers to work. But seriously, JSFiddle is just a far better site IMHO

**Comment by ZiadJ** [comment]
I can confirm. I've tried Plunker in both IE and Firefox for several days now and the preview panel is either extremely slow or doesn't render at all. Never had such issues with JSFiddle.

**Comment by jonricaurte** [comment]
Which OS are you guys using? Works fine for me in Windows 7/8. Is there any
errors on the console when accessing it?

**Comment by ZiadJ** [comment]
Windows 7 64bit here. The panel takes at least 3mins to update every time I make a change but I couldn't notice any JS errors other than the 11  warnings in the lint check panel which are not really errors anyway. In IE9 however the whole page is blocked by a semi transparent overlay making it completely unusable.

**Comment by orneryd** [comment]
jsFiddle and plunker are both good products. Plunker is newer and has more features like collaborative editing. jsFiddle has had its own issues and bugs in the past (such as including css files) that were not present in plunker when we started doing it. Since these are just examples, May i suggest using a browser from this decade to check out the examples?

Edit: I can be a tad Sardonic, pay no attention to me. We have been testing the grid in all browsers and have support for IE8 + Chrome and Firefox with caviats on the drag+ drop. This is more of a bug for plunker.

**Comment by jonricaurte** [comment]
What Tim was trying to say was... not that...  They are testing for cross
compatibility between browsers. Firefox works for me in Windows 7 64bit,
but not sure about IE9.

**Comment by ZiadJ** [comment]
I didn't notice before but I'm getting this error in IE9 now at http://plnkr.co/edit/#/20ZL0LVlRAXly3mATXNC?p=preview :
![Capture](https://f.cloud.github.com/assets/1817207/8085/bf8f59aa-4461-11e2-88f7-39f6921532a8.PNG)

I managed to get it to work in Firefox on another machine with the same OS but it's still failing in IE9 without any error messages this time. I also noticed that the basic example works in FF on the second machine but still no luck with the server side processing example.

Plunker has some very nice features but unfortunately it doesn't seem to work everywhere as expected.

**Comment by interactivetribe** [comment]
I HATE PLUNKER, please stop using it. You waste peoples time when 50% of the links to plunker does not work. How is AngularJS thinking of using plunker on their docs, did they not try it out on all browsers? CHANGE TO JSFIDDLE please this is so annoying....

**Comment by sheibeck** [comment]
I'm going to agree with the anti-plunker crowd. I've yet to get plunker to work a single time. It always gives and "undefined" error everytime I click a plunker link. It's terra-bad.

**Comment by fersucho** [comment]
Plnkr has worked great for me. It's a lot easier to create, edit and use modules in Plnkr than in JSFiddle. Maybe you could try it in Chrome, no trouble there.

**Comment by Mikey1984** [comment]
I am also in the anti-plunker camp. Very buggy, loads of errors and long reloads. I have given it a fair try but I go back to jsfiddle. Also, Jsfiddle is no beauty but I really hate plunkers design.
