### ISSUE TITLE
sortInfo and filterInfo observables should be bidirectional

### ISSUE THREAD

**Issue by thelinuxlich** [Knockout-Contrib/KoGrid#15]
What I mean is that if I change these observable values manually the changes should reflect on KoGrid UI (changing the arrow direction on header column, or filling text on filter input).

Currently I'm doing server-side sorting and filtering with AJAX and returning the entire dataset again to be loaded on KoGrid data observableArray. The problem is that the full grid is reconstructed and I lose filter text and the image indicating which column has been sorted.

**Comment by ericmbarnard** [comment]
I'll take a look at supporting this. The grid should filter/sort if you set these manually, but I can see where the UI is not updating when you set them manually.

**Comment by orneryd** [comment]
they are now bi-directional observables in 2.0.5
