### ISSUE TITLE
evalFilter performance issues on sortData

### ISSUE THREAD

**Issue by davidjsilva** [Knockout-Contrib/KoGrid#150]
I've noticed a performance issue when sorting (we do external sorting and have large objects) and I've nailed it down to evalFilter being called twice.  The sortData function calls evalFilter and also evalFilter is called in options.data.subscribe.  After removing the call to evalFilter from sortData performance is no longer an issue and the sorting is being done properly.  Is it save to remove that call to evalFilter in sortData?

**Comment by orneryd** [comment]
Yep, it seems like a bug
