### ISSUE TITLE
2.1.0 Maintaining selected rows across server side sort/page/filter

### ISSUE THREAD

**Issue by erikbcox** [Knockout-Contrib/KoGrid#158]
I initially attempted to save the selectedItems before rebinding the grid data and then readding them if the archived items were in the grid still. The grid doesn't show that the items are selected when I do this. 

So I guess I'm asking about two way binding on the selectedItems list. 

Is there another approach. I've attempted to expose the selectionService but I've met pitfalls with that approach as well.

**Comment by orneryd** [comment]
The problem with maintaining that in server-side paging is that you would need to keep the existing data client side cached somewhere and then present that data back to the grid.

The mechanism to specify wether or not it is selected is that I modify your data model with the property: '**kg_selected**': true/false. When the row is constructed I check for the existence of that property and set it to false if not present. What you could do is make sure your data is tagged with that property and mark the ones you want as true and the grid would persist the selections.

**Comment by erikbcox** [comment]
http://jsfiddle.net/PeL6z/1/

Is this what you were describing? I'd expect the 1st item to be selected.

**Comment by orneryd** [comment]
Looks like there was an issue but bug should be fixed now! http://jsfiddle.net/timothyswt/PeL6z/2/

Let me know if that helps
