### ISSUE TITLE
2.1.0 Add click event to a row in the grid via cell template

### ISSUE THREAD

**Issue by erikbcox** [Knockout-Contrib/KoGrid#159]
Body of my cell template
<a data-bind="click:$root.triggerActionMethod, text: $parent.entity['field']" ></a>

When I click the link the method is not called.

**Comment by orneryd** [comment]
Hi Eric, 

You need to make sure the function is in your viewmodel and you need to access the viewmodel through $userViewModel in the templates as per the documentation. If that is not working let me know and if you can provide a fiddle reproducing the problem that would help out a lot.

**Comment by erikbcox** [comment]
http://jsfiddle.net/Xdjqu/9/
offending line:  
var templateString = '<a data-bind="click:$userViewModel.clickMe, $text: $parent.entity[\'name\']"  ></a>';

I'm admittedly missing the boat on the $userViewModel usage. This is the doc page I was looking at: https://github.com/ericmbarnard/KoGrid/wiki/About-Custom-Templates

**Comment by orneryd** [comment]
looks like we forgot to bring $userViewModel down a level. There is an update in the latest commit that fixes that. It was accessible through $parent.$userViewModel but now it's accessible by itself.

http://jsfiddle.net/timothyswt/Dt3nw/1/
