### ISSUE TITLE
Destroy doesn't hide row

### ISSUE THREAD

**Issue by plurby** [Knockout-Contrib/KoGrid#16]
When calling destroy on selected row it remains visible in the grid. 

"Note that when KO renders a foreach binding, it automatically hides any objects marked with _destroy equal to true. So, you can have some kind of “delete” button that invokes the destroy(someItem) method on the array, and this will immediately cause the specified item to vanish from the visible UI."

I have added a property to my viewmodel Remove and then when i click on
Delete button i do the following:

<code>
 self.removeRow = function (row) {
            //destroy doesn't hide row
            //self.myData.destroy(row);

```
        row["Remove"] = true;
        self.myData.remove(row);        
    }
```

</code>
so i'm marking this row deleted. The problem is that i don't want this row removed from collection but i want to hide it. How can i do this?

**Comment by ericmbarnard** [comment]
@plurby - sorry for the delay on this.

We are actually moving away from using a `foreach` for rendering the grid rows, but I will try to get this supported - thanks for bringing it to my attention

**Comment by ericmbarnard** [comment]
KoGrid now supports _destroy related logic

**Comment by plurby** [comment]
Great, no need for a workaround anymore.
