### ISSUE TITLE
$parent.selected() does not seem to work as expected in templates

### ISSUE THREAD

**Issue by ZiadJ** [Knockout-Contrib/KoGrid#163]
Using $parent.selected() in templates to hide/show html according to the selected state of a row does not work as expected. Using the the template below we should see either 'selected' or 'unselected' at any given time:
<code>
function tmplEditable() {
        return "selected"
        + "unselected";
}
</code>
But somehow we're seeing both as shown below:

http://plnkr.co/edit/UJ4aBZ?p=preview

**Comment by orneryd** [comment]
this seems to work here:

http://plnkr.co/edit/H2nWzJ?p=preview

**Comment by ZiadJ** [comment]
Thanks, I got mine to work too by just enclosing it within a div. Guess that's the trick.
