### ISSUE TITLE
Sorting Arrows are opposite of Common Standard

### ISSUE THREAD

**Issue by davidjsilva** [Knockout-Contrib/KoGrid#166]
In KoGrid, when a column is sorted ASC the arrow is pointing down, and when the column is sorted DESC the arrow is pointed up.

For general consistency, I'd say that the arrow should point up for ascending, and down for descending. This is consistent with Windows (click a column header in Explorer) and other popular grids like Kendo, Datatables, SlickGrid, etc.

**Comment by orneryd** [comment]
In kogrid it's been this way for a while. I don't really see any reason to change it since it is completely semantic. To some, an arrow in the direction of increase (ascending pointing up, descending pointing down) makes more sense. 

But thank you for the input!

**Comment by davidjsilva** [comment]
In case anyone is interested, we wanted the opposite behavior of kogrid so we overrode it with a quick css fix...

.kgSortButtonDown {
  border-width: 0px 5px 5px 5px;
}
.kgSortButtonUp {
  border-width: 5px 5px 0px 5px;
}

...basically just flipped the css border-width styles to flip the triangle the other way.
