### ISSUE TITLE
Column Sortable=false css Cursor should not be Pointer

### ISSUE THREAD

**Issue by davidjsilva** [Knockout-Contrib/KoGrid#167]
If I have a column that has sortable=false I think the css cursor style should be set to 'default' instead of 'pointer'.  It makes it confusing for a user when hovering over an un-sortable column and seeing the pointer especially when they click and nothing happens.  I'm thinking you can add to the header template a css binding like 'kgSortable': sortable.

**Comment by orneryd** [comment]
fixes are in but we are going to make a new build here shortly

**Comment by orneryd** [comment]
fixed in latest 2.1.1

**Comment by davidjsilva** [comment]
The changes look great!  I did notice an issue though.  Check http://jsfiddle.net/zSpMh/2/ and you'll notice that the cursor changes from pointer to default if you follow these steps:
1. Hover over 1st column and you'll notice its a pointer now
2. Resize the 1st column
3. Hover over 1st column again and you'll notice it's default cursor now

Also want to give a shout out to Issue 137 https://github.com/ericmbarnard/KoGrid/issues/137 which is still an issue.  The column width does not seem to be retained if externalSorting is set to true.
