### ISSUE TITLE
Add support for an edit template in the columns definitions

### ISSUE THREAD

**Issue by ZiadJ** [Knockout-Contrib/KoGrid#168]
The ability to specify an edit template besides the existing <code>cellTemplate</code> would be nice addition. The cell would automatically switch to the edit template when clicked or double clicked and then would restore the original template when it loses focus. Is this feasible?

**Comment by orneryd** [comment]
That's what the templates are for, you can specify a template with two different controls with knockout that way by using the "if" binding just like issue #163

**Comment by ZiadJ** [comment]
I created a binding handler that will turn any existing template into an editable one:

https://github.com/ZiadJ/kgEditable

Its not fully tested so feel free to send some suggestions and/or contribute.

**Comment by orneryd** [comment]
This sounds like a great idea for a plugin if you want to turn it into one
instead if just a binding handler :)

On Wednesday, December 19, 2012, ziadj wrote:

> I created a binding handler that will turn any existing template into an
> editable one:
> 
> https://github.com/ZiadJ/kgEditable
> 
> Its not fully tested so feel free to send some suggestions and/or
> contribute.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ericmbarnard/KoGrid/issues/168#issuecomment-11523453.

## 

-Tim Sweet

**Comment by orneryd** [comment]
https://github.com/ericmbarnard/KoGrid/wiki

example plugins: https://github.com/ericmbarnard/KoGrid/tree/master/plugins

On Wed, Dec 19, 2012 at 3:51 AM, ziadj notifications@github.com wrote:

> Is the plugin architecture documented anywhere?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ericmbarnard/KoGrid/issues/168#issuecomment-11527436.

## 

-Tim Sweet

**Comment by davidjsilva** [comment]
@ZiadJ cool binding handler I may be interested in using that too.  I haven't tested it but do you have a fiddle or something where I can see it in action.  How does it work exactly?  If a click into a cell it converts it into an editable field?  What if I hit the tab key does it automatically jump into the next cell and make that editable?  And what if I am at the last column of a row and click tab?

**Comment by ZiadJ** [comment]
I've just added a link on the main page. There must be something wrong with JSFiddle because it fails in IE9 and yet the same code works perfectly when run locally.

No, it does not support key navigation yet but it should not be that hard to implement. Hopefully I'll convert it to a plugin as well once I figure out how it works.

**Update:**
Keyboard navigation is now fully supported using the Enter|Tab, shift > Enter|Tab, Up and Down keys while the left and right keys control the cursor position inside the input elements. I'll make this more customizable depending on user feedback. You can check out this CRUD example here:
http://jsfiddle.net/3bb3p
