### ISSUE TITLE
Column Reordering and Resizing 

### ISSUE THREAD

**Issue by CMRahman** [Knockout-Contrib/KoGrid#171]
Hi, 

First of all, thank you everyone for the excellent work you are doing. 
I'd be just awesome to have our own "Grid" in the KO world. :-)

I have a question or two regarding the KoGrid columns. 
1. We need to let the users resize the columns. I know you can already do this in KoGrid. But do we get any cb that supplies us the new width/size? We need to save the new width of the columns and use that to render the grid to the user next time he visits. 
2. We need to let the user reorder the header columns via Drag and Drop. And once again, we need to persist the new column order and use that to show the grid next time the user visits this page. 

Needless to say, we will save all these data [Size, Order of Column headers etc.] as a template in a DB or such.

Will anyone be interested in throwing us a few pointers here?

Thank you once again.

**Comment by davidjsilva** [comment]
Wow I just logged in to open the same exact request.  Plus 1 for this feature for sure, we definitely need this! We need to save the width/size of the columns plus the column order.

**Comment by igoryan-k** [comment]
"2. We need to let the user reorder the header columns via Drag and Drop. And once again, we need to persist the new column order and use that to show the grid next time the user visits this page."

You could subscribe to the koGrid.columns changes. This way you will be notified when a column was rearranged inside the collection. However, this does not help with point 1 (i.e. when a column's width changed)

```
    koGrid.columns.subscribe(function (columns)
                        {
                            find the changes and synchronize
                        });
```

And there is a third action we need to be notified about - disabling a column by pointing between to columns and dragging with "ctrl" key pressed. That  way a column is removed, we need an event for that too.

**Comment by orneryd** [comment]
these are added in 2.1.1 which has just been pushed. you will find a new option columnsChanged. It is a function which passes the new columns as the first argument.

It gets fires when the width is set on a column, a column is hidden, or columns are reordered. I would take a look at [column.js](https://github.com/ericmbarnard/KoGrid/blob/master/src/classes/column.js) since what is passed as the argument is an array of that object.
