### ISSUE TITLE
columnsChanged called twice when moving column

### ISSUE THREAD

**Issue by igoryan-k** [Knockout-Contrib/KoGrid#173]
Hi, thanks for the last update, introducing the columnsChanged event!
However, there is a bug with event - it's being called twice when a column is moved inside the grid. 

When a column is dropped, onHeaderDrop passes new collection to grid.columns. 

```
self.onHeaderDrop = function (event) {
...
       var cols = grid.columns();
       cols.splice(self.colToMove.col.index, 1);
       cols.splice(headerScope.index, 0, self.colToMove.col);
       grid.columns(cols);
...
 };
```

There is an internal subscription that calls self.fixColumnIndexes() when that happens.

```
  self.columns.subscribe(function () {
            if (self.$$indexPhase) return;
            self.fixColumnIndexes();
            kg.domUtilityService.BuildStyles(self);
        })
```

So fixColumnIndexes() triggers and changes the collection again:

```
self.fixColumnIndexes = function () {
        self.$$indexPhase = true;
        //fix column indexes
        var cols = self.columns();
        $.each(cols, function (i, col) {
            col.index = i;
        });
        self.columns(cols);
        self.$$indexPhase = false;
    };
```

Besides that, the  kg.domUtilityService.BuildStyles(self); will be called twice.
There is a $$indexPhase flag to stop the circular dependency, but all other subscribers to kogrid.columns will be called twice.

Lke the one for columnsChanged event:

```
self.columns.subscribe(function (newCols)
            {
                self.config.columnsChanged(newCols);
            });
```

**Comment by orneryd** [comment]
latest build should fix your problems
