### ISSUE TITLE
Editable Grid CellTemplate with autocomplete

### ISSUE THREAD

**Issue by jigjosh** [Knockout-Contrib/KoGrid#18]
how can we use jqueryui widget: 'autocomplete' in Celltemplate

pl help me out

thanks

Jignesh

**Comment by ericmbarnard** [comment]
@jigjosh 

Sorry for the delay - i've been busy on a couple engagements

You'll have to create a custom binding for jqueryui ( or use a knockout plugin for jquery ui like https://github.com/madcapnmckay/Knockout-UI)

Once you have that setup, it should be as easy as setting up a cellTemplate and using the autocomplete bindings from the jquery-ui KO plugin.

Let me know if you are running into troubles

**Comment by bkak** [comment]
Looking at the sample of autocomplete and KOGrid I have created this fiddle.

http://jsfiddle.net/bhoomikakaiya/uYFt6/

3rd column "Item" is made an autocomplete. It does not work.

Pl help me out.

Thanks

Bhoomi
