### ISSUE TITLE
Server Paging + Virtual Scroll

### ISSUE THREAD

**Issue by CMRahman** [Knockout-Contrib/KoGrid#184]
I don't know if this is the right place for this or not. A forum perhaps would have been a more appropriate place. So if this is out of place, please take it out. 

We want to enable combination of Server Paging with Virtual Scrolling. The paging part is quite clear from the samples and docs but I haven't found anything regarding Virtual Scroll. If I'm not mistaken I remember I saw virtual scrolling as an example before for KO Grid. 

Does the latest build support virtual scroll in combination with Server paging?

Thank you all for the great work you are doing with KO Grid.

**Comment by jonricaurte** [comment]
Yes, it supports virtual scroll in combination with server paging which can be seen at the server paging example:

http://ericmbarnard.github.com/KoGrid/#/examples

**Comment by CMRahman** [comment]
Ok, so I must have misused the term "virtual scroll". 
Basically my scenario was, say I have 250 items per Page and I'm on page 1. I want to scroll all the way to the bottom and when it reaches 250th item, i want to be able to hit the server and bring in the next batch of 250 items. In other words, from a end user perspective, you are going from Page 1 to Page 2 via scroll alone.
Is there a hook anywhere that lets me know when I've reached the end of the first batch while scrolling so I can generate a xhr to fetch the next batch from the Server and feed it to the grid as the next page?
Any pointer would be greatly appreciated.
