### ISSUE TITLE
Keep rowIndex in sync with currentPage when enablePaging=true

### ISSUE THREAD

**Issue by ericmbarnard** [Knockout-Contrib/KoGrid#19]
When paging the the `rowIndex` always starts at 1, even when I'm on page 2 or 3 of data - this should stay in tune with the page that I am on data-wise.

**Comment by shaneblake** [comment]
I just came to say i'd found a solution for this and see your comment from 14 mins ago.  What timing...

Anyway, thought I'd share my solution.  I updated the following lines in kg.RowManager

```
        row = new kg.Row(entity);
        row.offsetTop = self.rowHeight * rowIndex;

        if ( grid.config.enablePaging ) {
rowIndex += grid.config.pageSize() * (grid.config.currentPage() - 1);
        }
        row.rowIndex = rowIndex + 1; //not a zero-based rowIndex
```

**Comment by ericmbarnard** [comment]
haha - nice timing.

I tried this at first as well... however, I use the rowIndex as a key for caching data rows and rendering them in the grid and this was breaking that caching.

I've now added a 'rowDisplayIndex'  - and keep that in tune. Essentially same logic, but when debugging, I can also now use 'rowIndex' and 'rowDisplayIndex' independently

**Comment by shaneblake** [comment]
Yes, i just looked at that and update my code to match...  I've updated defaults and added jquery-ui classes to mine...

i did notice an extra " on a line in defaultFooterTemplate of the code you just posted that you might want to remove...

thanks...

shane
