### ISSUE TITLE
Selecting a row on the Large Data Example scrolls up

### ISSUE THREAD

**Issue by explorigin** [Knockout-Contrib/KoGrid#2]
Steps to reproduce:
1) Go to: http://ericmbarnard.github.com/KoGrid/examples/LargeData.html
2) Select #2
3) Scroll down to some number significantly off the screen (for me #35 worked)...select it
4) Observe that you are now automatically scrolled back up to #2

In the above example, #35 will be successfully selected, but we want to stay there, not jump back to #2.

**Comment by ericmbarnard** [comment]
@explorigin 

Ok, I see this. Its a result of trying to keep selectedItems scrolled into view when we sort and filter. I'll try to get it fixed here pretty soon.

Thanks

**Comment by ericmbarnard** [comment]
@explorigin 

This should now be fixed in the newest build
