### ISSUE TITLE
Option to always have filter row showing

### ISSUE THREAD

**Issue by shaneblake** [Knockout-Contrib/KoGrid#23]
My business requirements are such that I don't need the row index column and need the filter row to always be showing.

I've done some poking around in the code setting the filterIsOpen(true), but it doesn't render any data...

It would be nice if this was an option we could set when we bind the grid.

Thanks

**Comment by ericmbarnard** [comment]
I'll look at getting this supported. The `filterIsOpen` observable does in fact trigger the layout of the grid to change, however it doesn't have a two-way binding back to the actual filter row cells to make them appear.

This is actually much related to issue #11, which is a non-trivial use-case to implement.

**Comment by azzimuth** [comment]
You can do that by adding `$('div.openBtn.kgFilterBtn').trigger("click");` in `$(document).ready()` (until this will be supported by KoGrid natively)

**Comment by orneryd** [comment]
completely redesigned in 2.0. There is no more index row. That is left to the user and filtering is done through the menu in the top right corner of the new grid.
