### ISSUE TITLE
Need away to detect "Filter Clear" as a single event

### ISSUE THREAD

**Issue by EntitySpaces** [Knockout-Contrib/KoGrid#24]
Currently, the only way I know to detect filters changing (including clearing them all) is by creating a computed column on "filterInfo". The problem is if you have 5 filter going these are changed 1 by 1 causing 5 hits to the database. Can you clear all of these by merely setting the filterInfo to [] in one swoop to avoid causing multiple triggered events?

**Comment by ericmbarnard** [comment]
@EntitySpaces 

FilterInfo is observable, so you should be passing in something like:

`filterInfo: ko.observable()` (or a previously created observable) in your `data-bind` statement.

I'll look at only updating the filterInfo once on `clear` however, if you're using this for server side filtering you will definitely want to throttle the filterInfo changes as these are triggered `onkeydown` ... which can get pretty expensive.

try something like `filterInfo.extend({ throttle: 5 });`

**Comment by EntitySpaces** [comment]
Ya, that's what I was asking for, when I hit the eraser icon it would be great if we only got one filterInfo change ...

**Comment by orneryd** [comment]
The filterOptions.filterText is an observable. all you need to do is pass an observable to that and subscribe to it.
