### ISSUE TITLE
KoGrid render incorrectly on partial reload (SPA)

### ISSUE THREAD

**Issue by AndersMalmgren** [Knockout-Contrib/KoGrid#241]
If i do a hard load of the page (CTRL+F5) the grid renders correctly, but if i leave the page and go back using the SPA feature (Sammy.js with hash routing) the grid render incorrectly.

All the columns are mashed together to the left

**Comment by AndersMalmgren** [comment]
Strange if I use the 

columnDefs option it works

**Comment by vancourse** [comment]
I have seen the same issue in a slightly different scenario : If the total items retrieved is less than the page size, then all columns are mushed up.
Any ideas?
