### ISSUE TITLE
Should have an option for disabling filter by column

### ISSUE THREAD

**Issue by thelinuxlich** [Knockout-Contrib/KoGrid#25]
Maybe a filterTemplate attribute on columnDefs?

**Comment by ericmbarnard** [comment]
I like this idea - I've had a lot of requests for changing a filter text box out for a select list... this would fit that nicely.

**Comment by orneryd** [comment]
this is implemented int he lates skogrid-merge branch. option on the columndefintion is "filterable" set it to false and the filter won't appear above the row.

**Comment by ericmbarnard** [comment]
Closing as this will be fixed in PR #69
