### ISSUE TITLE
Support multi selected items and one highlight item

### ISSUE THREAD

**Issue by tuanvt** [Knockout-Contrib/KoGrid#27]
Hello everyone ,

I don't know if anybody want to implement something like me based kogrid or not. 
My idea is that , the grid allow user to multiple check the items, so that they can get a collection of items for action. On the other hand, they can select a single row to view the details. Here is how I currently playing around with this idea:
http://jsfiddle.net/hawaii/GxWqm/

I need to figure a proper way to get the highlighted item , for now I am using the field Id for comparing. 

Is this something that can be considered adding to the flexibility of the grid ?

Thanks you guys, kogrid is a great solution for me.

**Comment by ericmbarnard** [comment]
@tuanvt 

I would probably go with a custom cell/row template if you want to create behavior where someone could click on a row and see the details. I don't think that would be too hard given the data that is passed into those templates.

https://github.com/ericmbarnard/KoGrid/wiki/Custom-Templates

Let me know if i'm not understanding your question correctly.

**Comment by tuanvt** [comment]
Hello Eric,

I understand what you mean there, however that means I have to have an highlighted item on my viewmodel right ? And I also need to differentiate on row click event from checkbox click or cell click as well?.

**Comment by orneryd** [comment]
I added functionality to turn off selection on click and only select with checkbox. at that point you can just create a row template and bind to an observable that you name called "highlighted". that way you can capture the click event yourself and do whatever styling you see fit. option default is "selectWithCheckboxOnly: false" just set it to true in your initial bindings.

commit https://github.com/Crash8308/sKoGrid/commit/564462476cfdc96e297685a5ab90f162133a74fe

https://github.com/Crash8308/sKoGrid

**Comment by ericmbarnard** [comment]
Closing as this will be fixed in PR #69
