### ISSUE TITLE
Filter dates based on a period

### ISSUE THREAD

**Issue by azzimuth** [Knockout-Contrib/KoGrid#32]
Currently filtering the dates works so that the dates in a column are filtered on "later than or equal" logic. What I need in my project is "from - to" logic, i.e. two filter fields for each date point. Would that be easy to implement by myself?

**Comment by ericmbarnard** [comment]
@azzimuth 

You would probably want to implement this using external filtering. KoGrid's column header filters are currently just using string-based filtering (no date pickers, etc...), and it would be quite a bit of work to try and re-engineer those at this point.

I could look at intelligently toggling what the filter on the Column Header looks to the user based upon the data type in the column (date range pickers for date columns, time range picker for times, number range picker for numbers... etc...)

**Comment by azzimuth** [comment]
Hi Eric,

Could you explain a bit more how would I hook an external filter? In the documentation you only point out the 'useExternalFiltering' property which would enable the external filtering but there is no example how this filtering should be implemented.

**Comment by ericmbarnard** [comment]
@azzimuth 

Check this example out: http://ericmbarnard.github.com/KoGrid/examples/Complex-Server-Side-Paging.html

If you look at the javascript on the page, there is function in the `myVM` called `getPagedDataAsync', this is where you can follow the external filtering/sorting logic should you want to implement that on your own (or on the server side).

Currently inside this function, i simply call back to my own JS implementations of sorting and filtering logic (`sortManager` and `filterManager`). However you could build any sort of logic that you wanted that can work with the `filterInfo` and `sortInfo` observables that KoGrid manages.

The `getPagedDataAsync` is also easily replaceable with an AJAX function that calls to server end-point.
