### ISSUE TITLE
IE9 Support

### ISSUE THREAD

**Issue by speedcat** [Knockout-Contrib/KoGrid#33]
KoGrid doesn't work for me on IE9.

**Comment by ericmbarnard** [comment]
@speedcat 

Could you let me know some specifics about your machine, and if you have IE9 setup to use different modes (IE7 mode? or something similar).

I run my entire unit test suite and hand checks in IE9, Chrome, and FF before I push code to Github, so I'm interested to know what browser combination isn't working.

**Comment by speedcat** [comment]
I use the IE9 9.0.8112.16421 on Windows 7 64bit in the IE9 mode. I guess there is maybe a problem with knockout.mapping and kogrid. But there is no problem on ff and chrome. I will investigate it with the debugger!
