### ISSUE TITLE
Grid is nested inside a DOM element where the style is "display: none" or "height: 0; width: 0" then it will incorrectly measure itself

### ISSUE THREAD

**Issue by jonricaurte** [Knockout-Contrib/KoGrid#35]
The jsfiddle is here:

http://jsfiddle.net/xcrico/Pfhkj/

**Comment by donpedro** [comment]
Workaround for this error: run a resize on the container once it becomes visible.  JQuery example:

$('#Container').resize()

**Comment by orneryd** [comment]
Interesting. I updated your fiddle. http://jsfiddle.net/Pfhkj/8/ 
If you specify percentages of the container then it behaves that way but not if you specify actual pixels. However if you make the one with the %'s the default view it will measure correctly:
http://jsfiddle.net/Pfhkj/9/

**Comment by lhope** [comment]
This issue affects me. But the workaround does, in fact, workaround correctly.

**Comment by orneryd** [comment]
Fixed in 2.0
