### ISSUE TITLE
Search box filter with KoGrid binding to filtered items incorrectly displays after entering initial letter

### ISSUE THREAD

**Issue by jonricaurte** [Knockout-Contrib/KoGrid#36]
Here is the jsfiddle:

http://jsfiddle.net/xcrico/u3UrU/5/

If I have a search box to search through an observable array, and kogrid is bound to the filtered items, it will not display any contents of the filtered items after typing in 1 letter, however, if you type in 2 letters it will correctly display the list of names. This only happens on the initial search. If I delete all the contents within the search box and type 1 letter, it will work correctly the second time.

Example:
In the jsfiddle, if you type 1 letter which is a lower case "j", the bottom will say there are 2 total items, however the grid displays none. If you type in another letter after that lets say a lower case "o", the grid will update and it will say total items is 1 and display 1 row.

**Comment by orneryd** [comment]
I updated your jsFiddle. This doesn't seem to be a koGrid problem. 

use underscore and underscore-ko and use the prototype extension "filter" instead.

http://jsfiddle.net/timothyswt/u3UrU/6/
