### ISSUE TITLE
Editable grid celltemplate with autocomplete

### ISSUE THREAD

**Issue by bkak** [Knockout-Contrib/KoGrid#39]
This is with reference to a closed issue. I am also facing the same issue.

I have created a jsfiddle with autocomplete.

http://jsfiddle.net/bhoomikakaiya/uYFt6/

Here, 3rd column "Item" is made an autocomplete. It does not work.

Pl help me out.

Thanks

Bhoomi

**Comment by ericmbarnard** [comment]
@bkak 

Sorry for the delay on this, I've switched jobs and am just now getting a chance to work through my GH issues. I've had a lot of requests for this, so I'll put together an example and post it for folks' future reference

**Comment by bkak** [comment]
Thanks for replying.

I could take autocomplete little forward, now i can see the autocomplete working, but all the autocomplete's of all the rows are sharing the same observableArray so on changing 1 textboxes value other values also change. Here is the fiddle demonstrating the same :

http://jsfiddle.net/bhoomikakaiya/uYFt6/27/

Another help to hide the columns selectively in column definition would also be highly appreciated.

Thanks in advance..

Bhoomi.

**Comment by bkak** [comment]
Hi,

I know you might have been busy..did you get a chance to look into this issue? 

Thanks in advance..

Bhoomi.

**Comment by orneryd** [comment]
as of version 2.0 are you still having issues with this?

**Comment by bkak** [comment]
Thanks for the reply. There was some other issue at my end, because of which it was not working. Autocomplete worked in previous version too. 

I highly appreciate the recent updates KOGrid is releasing. 
Shall upgrade to latest version soon.

Thanks..
