### ISSUE TITLE
 paging doesn't seems working

### ISSUE THREAD

**Issue by tpever** [Knockout-Contrib/KoGrid#4]
Hi,

In samples GridWorkBench.htm, It seems at footer it shows paging controls, while navigating it doesn't seems working. 
Is there any plan to update it ?

Sorry for bothering you again.

Thanks and regards.

**Comment by ericmbarnard** [comment]
@tpever 

Thanks for bringing this to my attention. I have some changes that I've been working on for the past week, but haven't pushed to GH. I'll add that to my test cases to make sure that is working before pushing latest.

Thanks!

**Comment by tpever** [comment]
Thanks a lot, look forward to see it soon.

Thanks and regards.

**Comment by tpever** [comment]
Hi,

Is there any update on paging part, or any workaround right now for same?

Look forward to get your response.

Thanks and regards.

**Comment by ericmbarnard** [comment]
@tpever 

Well, I am pushing code changes to the v1.0 branch - you should pull that and try the code there. I won't be updating the examples until I merge the v1.0 branch into master.

**Comment by tpever** [comment]
Thanks for update, yes I have seen V1 changes till doesn't seems data paging is implemented yet footer part is exists still data is not getting paged as per pagesize.

Also I was trying to use Row template and header template seems not working yet. please have a look at 

http://jsfiddle.net/2Rypp

Thanks and regards

**Comment by ericmbarnard** [comment]
@tpever 

When you say that paging isn't working - are you looking at the `GridWorkBench.htm` file in the repository?

Also, your Row Template can't use `<TH>` and `<TD>` elements - KoGrid is DIV based and so those should all be DIVs. There were several problems with your jsFiddle: 
- koGrid requires jQuery
- koGrid CSS was missing
- there was no `orditem` object that you were newing up
- there was no `rand` function to call

I got those fixed and here is an updated example with a working rowtemplate
http://jsfiddle.net/2Rypp/8/

**Comment by tpever** [comment]
First of all really sorry for late reply and incomplete url for  jsfiddle, url on which i was working is http://jsfiddle.net/2Rypp/2.

Anyway, I was looking at koGrid with my limited knowledge on javascript, it seems  just like sortingmanager and filtermanager which soft/filter data , data filter based on page size seems missing. 

if you look at the example i have modified the data range from 10 to 1000 and trying to evaluate paging seems footer showing the correct pages and move next previous working fine. only the data is not getting filtered based on pagesize specified.

http://jsfiddle.net/2Rypp/9/

I have tried to implement something like :

﻿kg.PagingManager = function(options){
    var self = this,initPhase = 0,
    internalPagedData = ko.observableArray([]);
    this.data = options.data; //observableArray
    this.pageInfo = ko.observable();
    this.pagedData = ko.computed(function(){
        var data = internalPagedData();
        //this is a bit funky, but it prevents our filtered data from being registered as a subscription to our grid.update bindingHandler
        if (initPhase > 0) {
            return data;
        } else {
            return self.data();
        }
    });

```
var currPageData = function () {
       if (!options.enablePaging) {
            internalPagedData(options.data());
            return;
       }
       var pgSize = ko.utils.unwrapObservable(options.pageSize());
       var pg = ko.utils.unwrapObservable(options.currentPage());
       var startIndex =pgSize * (pg-1);
       var newData = options.data().slice(startIndex, startIndex + options.pageSize());
       internalPagedData(newData);
};

this.updatePage = function(){
   //pageData();
    var pg = ko.utils.unwrapObservable(options.currentPage());
    if(pg == self.pageInfo()) return;
   self.pageInfo(pg);
};

//create subscriptions
this.data.subscribe(currPageData);
this.pageInfo.subscribe(currPageData);
//increase this after initialization so that the computeds fire correctly
initPhase = 1;
```

 };

Still not fully working as expected, it should be merge with SortManager and FilterManager and also not sure will work with templates.

Thanks and regards.

**Comment by ericmbarnard** [comment]
@tpever 

I now see what you are getting at.

KoGrid intelligently pages through VERY large data arrays internally. The paging controls on the grid are merely there for server side paging ( you can subscribe to the changes of the `currentPage` and `pageSize`). We usually do `enablePaging: false' if all of the data is client-side.

I'm not sure of a good reason to show the pager when all the data is completely client-side. KoGrid only renders what is visible on screen, so if you have 10000 items in an array, but you're grid is only large enough to show 20 rows at a time, KoGrid will actually page through those 10000 items as you scroll. This internal "row virtualization" was one of the core reasons I created KoGrid.

If you look at your fiddle in a debugger, you'll be able to see that there are only about 20 to 30 rows ever in the DOM as you scroll the grid. 

Let me know if I'm still missing the mark here on your question, or if you have a use-case I'm not thinking of.
