### ISSUE TITLE
Error in IE9 at $style[0].styleSheet.cssText = css.toString(" ");

### ISSUE THREAD

**Issue by jonricaurte** [Knockout-Contrib/KoGrid#40]
I am getting an Invalid Argument error here:

if ($style[0].styleSheet) { // IE
            $style[0].styleSheet.cssText = css.toString(" ");
        }
        else {
            $style[0].appendChild(document.createTextNode(css.toString(" ")));
        }

in IE9. It says there is an invalid argument at:

$style[0].styleSheet.cssText = css.toString(" "); 

cssText is an empty string and css has a toString method which is:

toString = function () {
        var separator = arguments[0];
        if (separator !== null && separator !== undefined) {
            return strArr.join(separator);
        } else {
            return strArr.join("");
        }
    }

**Comment by jonricaurte** [comment]
Ok, so I added this to the if statement:

if ($style[0].styleSheet && $style[0].styleSheet.cssText !== '') { // IE
         $style[0].styleSheet.cssText = css.toString(" ");
 }
 else {
         $style[0].appendChild(document.createTextNode(css.toString(" ")));
}

I don't get the error anymore. However, instead of getting the error, my cssText sometimes ends up as an empty string so my grid looks jumbled and everything is overlapping in the top left corner. This only happens in IE.

**Comment by ericmbarnard** [comment]
@xcrico 

Sorry for the delay on this, I've switched jobs and am just now getting a chance to work through my GH issues. I see what's  happening here - have to love IE, right? I'll get the 'if' statement added for at least a stop gap right now and then investigate to see what the deeper issue is.

**Comment by jonricaurte** [comment]
Thanks for the update.

**Comment by ZiadJ** [comment]
I used to have this problem because I was calling ko.applyBindings() each time new data was fetched from the server. I changed the code so that I only needed to call it once at startup and everything worked fine since then.

Hope this helps.

**Comment by keithharvey** [comment]
I had the same issue (with the if statement in place). I stepped through it and found that $style[0].styleSheet.cssText !== '' was returning true in IE8 (my intranets browser).

Changing it to 

```
    if ($style[0].styleSheet) { // IE
        $style[0].styleSheet.cssText = css.toString(" ");
    }
    else {
        $style[0].appendChild(document.createTextNode(css.toString(" ")));
    }
```

works in Firefox 14.0.1, Chrome 21, and IE 8
