### ISSUE TITLE
Updating Data

### ISSUE THREAD

**Issue by speedcat** [Knockout-Contrib/KoGrid#42]
Hi,

I want to update the data in the kogrid. If I update the ko observable array via "ko.mapping.fromJS(...)" nothing happens. But if I scroll the list is dissapearing.

**Comment by ericmbarnard** [comment]
@speedcat 

Can you reproduce in a jsFiddle and shoot me the link?

**Comment by orneryd** [comment]
This is not reproducable for us and has been open for 3 months without a reply so i am closing it.
