### ISSUE TITLE
How to do custom Sorting in KOGrid

### ISSUE THREAD

**Issue by tlktoash** [Knockout-Contrib/KoGrid#44]
I have used KO grid in our financial application. In grid , some column has data that is blank sometime. For that kind of data sorting is not working. I want to bind event so i can apply custom sorting. Any idea?

**Comment by orneryd** [comment]
you need to create your own sorting function and bind it under sortInfo

**Comment by orneryd** [comment]
Oops, misunderstood the problem. We will look into a few ways to fix this in the next release.
