### ISSUE TITLE
Refreshing koGrid does not render - requires an extra push + pop call as workaround

### ISSUE THREAD

**Issue by mark--a** [Knockout-Contrib/KoGrid#46]
We're working on ASP.Net MVC 3 + knockout-2.1.0 and we're trying to render a koGrid but have an Ajax issue (we think) that is emptying the koGrid instead of updating it.  The grid renders fine initially, but when we try to update the grid, it empties/hides instead.  Debugging with fiddler, the json object returns (with rows that we expect) but the grid goes empty after the call.

We have a workaround in place that works, but it clunky and not particularly elegant.  Hence our bug/issue report.

So adding a pop and push to force the refresh makes it all work, the grid updates in the expected way. So javascript chages to:

```
self.radioSelectedOptionValue.subscribe(function() {
    $.get('/Orders/GetProducts', { typeCriteria: "gender", id: 1 }, function(data) {
        self.Products(data);
        self.Products.push({});
        self.Products.pop();
    });
}, this);
```

We have a nice StackOverflow question going that has more commentary from others at: http://stackoverflow.com/questions/11298437/kogrid-empties-our-grid-instead-of-updating-with-knockoutjs-with-asp-net-mvc-3

Obviously, we would prefer the grid to update gracefully without the explicit call to push and pop.

Thanks!

**Comment by orneryd** [comment]
Looking into this deeper and trying to understand what is happening.. If you use the updated fiddle here:

http://jsfiddle.net/H4ZXM/26/

and set a breakpoint on line 2751 of kogrid.debug you will see that the rows are rendered correctly and then the very last time that code is hit, they are removed from the view. However, the data is still there because the number of items still says "2" in the footer.... 

```
//fire the with "update" bindingHandler
returnVal = ko.bindingHandlers['template'].update(element, makeNewValueAccessor(grid), allBindingsAccessor, grid, bindingContext);
```

**Comment by orneryd** [comment]
Fixed in 2.0

**Comment by tachang** [comment]
I am still running into this issue even with koGrid-2.1.0.debug.js

**Comment by a3code** [comment]
I have the same koGrid-2.1.1

**Comment by RHAD1969** [comment]
I have the same issue running koGrid-2.1.1.

**Comment by nib-alejo** [comment]
I have the same issue (koGrid-2.1.1)

**Comment by crissdev** [comment]
@nibalejo @RHAD1969 @a3code If possible please post a repro against [2.1.5](https://github.com/Knockout-Contrib/KoGrid/tree/2.1.5/dist) branch and I will reopen this issue. Thanks
