### ISSUE TITLE
Server Side Sorting Example Issue

### ISSUE THREAD

**Issue by shanez** [Knockout-Contrib/KoGrid#5]
If you go to your example below and go to the last page. When you try sorting it only sorts the elements on that page. Shouldn't it sort all the elements and then get the last page of data from that sort?

http://ericmbarnard.github.com/KoGrid/examples/Complex-Server-Side-Paging.html

**Comment by ericmbarnard** [comment]
@shanez 

Yes, KoGrid supports doing sorting completely on the server-side, so I need to fix this example and make sure that is shown.

-Eric

**Comment by EntitySpaces** [comment]
Here's an example ...
http://www.entityspaces.net/blog/2012/03/14/entityspacesjs+And+More+Cool+EntitySpaces+Features.aspx

Might not be what you're looking for but it will get you started
