### ISSUE TITLE
KoGrid project alive?

### ISSUE THREAD

**Issue by kylecordes** [Knockout-Contrib/KoGrid#51]
I see issues and pull requests as recently as the last few days - but the last commit on the project is 3 months ago. Is the project alive?

**Comment by ericmbarnard** [comment]
@kylecordes 

Yep, it is. I've been swamped with a job transition for the past 2 months, so that's been the delay. 

You should be seeing updates here soon.

**Comment by kylecordes** [comment]
Ah, great. It looks like there are some pull requests ready too.
