### ISSUE TITLE
Can't turn off filter

### ISSUE THREAD

**Issue by thnk2wn** [Knockout-Contrib/KoGrid#54]
Need a way to turn off filtering functionality entirely, by setting a configuration option of the grid. Is there a way an I'm missing it or is there an idea way to work around this? I saw a "filterVisible" and "showFilter" inside the javascript file but they don't appear to be exposed out.

The only way I see to work around at the moment is something hacky like

``` javascript
$('.kgFilterBtn').hide();
```

Or maybe via customizing the entire header template but really I'd like a filterVisible: false or showFilter:false in the root config options.

**Comment by orneryd** [comment]
I use displayRowIndex and set it to false, that will remove the filtering option since it sits atop that row

**Comment by orneryd** [comment]
You can also use in the column definitions "filterable: false" which will remove the ability for that row. Adding to milestone sko-grid merge

**Comment by ericmbarnard** [comment]
There are work arounds for this, but we'll keep it in the backlog. I'm moving this to a later release so that we can get this one out the door

**Comment by orneryd** [comment]
Fixed in koGrid 2.0
