### ISSUE TITLE
Selecting a row with only checkbox

### ISSUE THREAD

**Issue by thnk2wn** [Knockout-Contrib/KoGrid#57]
Selecting a row by clicking anywhere on the row is a nice feature in ways but sometimes it is more desirable to just use the checkbox, especially with custom templates, links, edit fields etc. Also selecting text with the cursor accidentally selects the row.

What would be great is a config setting to toggle this behavior. For now is there a recommended workaround?

**Comment by orneryd** [comment]
Resolved with commit: https://github.com/Crash8308/sKoGrid/commit/564462476cfdc96e297685a5ab90f162133a74fe
here: https://github.com/Crash8308/sKoGrid

**Comment by ericmbarnard** [comment]
Closing as this will be fixed in PR #67
