### ISSUE TITLE
memory leaks on large set of data on IE8

### ISSUE THREAD

**Issue by anasnakawa** [Knockout-Contrib/KoGrid#58]
try to open your example on IE8 [large data example](http://ericmbarnard.github.com/KoGrid/examples/LargeData.html),
open the windows task manager, you will find that IE initially has occupied around 110MB..

try to scroll up and down with the list, you will find out the IE occupied memory will reach to over **300MB**!!,
and once you stop playing with the scroll bar, the memory does not come down..

this issue is causing our web application to break on customers computers

any clue ??

**Comment by JimmyIm** [comment]
i see this problem too i am in release i should finished by tomorrow morning please help us  !!!

**Comment by orneryd** [comment]
I believe it has to do with the enclosure on the row manager and referencing the row entities. I was reading that the garbage collector in older versions of IE doesn't know how to handle de-referencing memory when DOM elements are referenced within an enclosure. The virtualization had a couple spots where it seems like a new instance of the rendering function was being created.

I don't have a machine with IE8 on it.. Can you try the latest form here? https://github.com/Crash8308/sKoGrid

**Comment by orneryd** [comment]
Fixed in 2.0
