### ISSUE TITLE
Memory Leeeeeeeeeeeeeeak

### ISSUE THREAD

**Issue by OmarKhanfer** [Knockout-Contrib/KoGrid#59]
When I move the scroll up and down the memory usage of the browser increasing I dont know why any solution.

**Comment by ericmbarnard** [comment]
@OmarKhanfer 

Can you let us know the browser version?

**Comment by OmarKhanfer** [comment]
Dear Eric,

Its IE8.

Thanks and Regards
Omar

**Comment by ericmbarnard** [comment]
I'm going to mark as a duplicate of Issue #58 and close it
