### ISSUE TITLE
KoGrid should gracefully render an empty table if the data array has nothing

### ISSUE THREAD

**Issue by thelinuxlich** [Knockout-Contrib/KoGrid#6]
Currently it throws an uncaught exception, so I have to call applyBindings on its <div> only when I have a complex array of objects loaded.

**Comment by ericmbarnard** [comment]
Thanks,

I have some of these fixed in a new branch that I will be pushing soon. Are you setting the `data` option to an empty `observableArray([])` or is the `data` option bound to a null/undefined object?

**Comment by thelinuxlich** [comment]
An empty observableArray

**Comment by ericmbarnard** [comment]
Ok, thanks I'm currently looking at it.

**Comment by ericmbarnard** [comment]
@thelinuxlich 

Are you getting the `'If auto-generating columns, "data" cannot be of null or undefined type!'` error? 

If you are, I'm not really sure this is a use-case that I want to support, but thats just from my early planning. Can you describe  why you might need to be able to do this?

**Comment by thelinuxlich** [comment]
yes, that is the error...the problem is that I want to call ko.applyBindings(viewModel) only once on the entire web application and only when the user clicks a button, data should be loaded into KoGrid observableArray

**Comment by ericmbarnard** [comment]
Ok, yes I understand that use-case, and developer ease is something that I'm definitely working to maintain.

If you want to both `autogenerate` columns AND initialize the grid without any array data, that is something I initially didn't want to support. You essentially would just have a blank header, footer.

I can look at supporting this to the point where it simply renders the empty containers, but probably as a future item.

Currently, if you don't have any data, you can specify the `columnDefs` and this will allow you to use an empty data array.

**Comment by thelinuxlich** [comment]
I'm okay with the solution that draws a blank header and don't throw an error

**Comment by brandonwittwer** [comment]
I don't think a grid control should render if there is no data.  9 times out of 10 I'd be hiding / not producing the grid for sake of clarity and just display my own message.  

This would be more than easy enough to do with a visible:array.length>0 binding.  If anything, i would want to go the extra step and make sure the grid does absolutely nothing, not wasting cpu cycles to render itself.

**Comment by orneryd** [comment]
I don't think we want to support this. a grid shouldn't render data if there are no items. If there are no items to display you can just simply hide the grid as bsingin64 mentioned.
