### ISSUE TITLE
Unselecting item does not update selectedItemCount if isMultiSelect == false

### ISSUE THREAD

**Issue by tonyhawe** [Knockout-Contrib/KoGrid#62]
If isMultiSelect is set to false and you select an item then unselect it the style remains kgSelected.
selectedItemCount is not updated either so in the footer "Selected Items:" remains at 1 instead of returning to 0.

It seems to work fine when isMultiSelect == true

**Comment by orneryd** [comment]
fixed in latest commit here: https://github.com/Crash8308/sKoGrid

**Comment by ericmbarnard** [comment]
Closing as this will be fixed in PR #67
