### ISSUE TITLE
ColumnWidth option not working with autogenerated columns

### ISSUE THREAD

**Issue by thelinuxlich** [Knockout-Contrib/KoGrid#7]
It generates columns still eating 1 character because of the small width.

**Comment by ericmbarnard** [comment]
@thelinuxlich 

Yes, autogenerating columns tries to calculate the width of the column name using the length of the string. However, I realize that I've also done a bit more work on the sorting buttons, which have probably thrown off the excess padding I was trying to give to the column names.

**Comment by ericmbarnard** [comment]
fixed with commit: 5bdb618a

**Comment by thelinuxlich** [comment]
Thanks a lot!

**Comment by ericmbarnard** [comment]
@thelinuxlich 

I've got your page with the grid working - do you mean that koGrid eats the extra characters in the cells or the header? I'm assuming you mean the cells since the Headers look good to me?

**Comment by thelinuxlich** [comment]
yes that´s the problem :(

**Comment by thelinuxlich** [comment]
This issue should be reopened

**Comment by ericmbarnard** [comment]
ok - currently, KoGrid will not re-size its columns based upon the contents of the data cell. It is actually a pretty large project to resize the columns on the fly based upon cell contents.

What KoGrid currently does is simply calculates how wide the column should be based upon the `displayName` of the column when the grid is initializing.

I originally thought you were saying the column headers weren't wide enough, but now I see what you are pointing out.

Some workarounds
- From your example, it looks like you are building the columnDefs based upon the field checkboxes that users are selecting... You could simply just increase the `width` of each column to allow for larger cell contents.
- You could use a custom cell template (KoGrid now supports generic templates using $cell and $cellValue) that would intelligently cut-off the cell contents and turn the cell contents into a tooltip:

``` html
<script type="text/html">
<div data-bind="kgCell: $cell">
    <span data-bind="myCutoffTextHandler: $cellValue, attr: { title: $cellValue }"></span>
</div>
</script>
```

**Comment by orneryd** [comment]
assigning this to the 2.0 milestone.
