### ISSUE TITLE
entering a page number causes the currentPage observable to be a string therefore breaking page forward.

### ISSUE THREAD

**Issue by wyattwebb** [Knockout-Contrib/KoGrid#71]
Scenario: 
- Results with 10 pages
- Start on page one, 
- Type 6 in the page textbox and click off it
- Click page forward 

This calculates that the string "6" + 1 (or 61) is larger then 10 and goes to 10.

Suggested fix:

In the protectedCurrentPage observable where currentPage is assigned just multiple page by 1.

 self.currentPage(page*1);

Hope that helps

**Comment by ericmbarnard** [comment]
@wyattwebb 

easy enough - thanks for the heads up. We'll get this tackled.
