### ISSUE TITLE
Implementing custom template to use button within KOGrid

### ISSUE THREAD

**Issue by dineshsharmain** [Knockout-Contrib/KoGrid#72]
Hi
I am trying to implement a button for each row with a click event, I tried to create custom template like .....

<script type="text/html" id="buttonCellTmpl">
    <div data-bind="kgCell: $cell" >
        <input type="text" data-bind="value: $cellValue" onclick="alertMe();" style="width: 80px"/>
    </div>
</script>

and consuming like ...
data-bind="koGrid: { data: myObsArray,
                                 columnDefs: [
                                                { field: 'Name',displayName: 'Name', width: 150 },
                                                { field: 'FileUri', width: 220,CellTemplate: buttonCellTmpl }
                                             ],
                                 autogenerateColumns: false,
                                 isMultiSelect: true,
                                 ....
Hope I am doing correct.... but not able to see this button.

**Comment by tpdi** [comment]
The Knockout databinding is "click", not onClick, and it's in object literal format, and you need a comma:

<input type="text" data-bind="value: $cellValue, click: alertMe"/> 

This assumes that your row model has a function (or observable) attribute named "alertMe".

Also, I think that koGrid wants you to specify column widths in the column definition.

**Comment by orneryd** [comment]
tpdi is correct. it should look like this (you said oyu are wanting a button)

<div data-bind="kgCell: $cell" > 
    <button class='btn' data-bind="value: $cellValue, click: alertMe" /> 
</div>

closing this as it was a faulty implementation

**Comment by arunsaho** [comment]
Hi,
I want a button/link which select entire row and open a dialog box with details of the row but somehow it working for first row with all the css applied to button in first row but all other is not open the popup. could you please help me on this.
