### ISSUE TITLE
how to set default sort column with sort direction

### ISSUE THREAD

**Issue by suryabg2000** [Knockout-Contrib/KoGrid#74]
Hi Team,

I have defined kogrid as follows

```
                        <div id="contactsDiv" data-bind="koGrid: { data: searchContacts,
                         columnDefs: [ 
                                        { displayName: 'Name', field: 'Name',  },
                                        { displayName: 'Email', field: 'Email' },
                                        { displayName: 'Phone', field: 'Phone' },
                                        { displayName: 'City', field: 'City' },
                                        { displayName: 'Salary', field: 'Salary' }
                                        ],
                         autogenerateColumns: false,
                         isMultiSelect: true,
                         showFilter: false,
                         enablePaging: true,
                         rowTemplate: 'tmpContactRow', 
                         useExternalFiltering: true,
                         useExternalSorting: true,
                         filterInfo: filterInfo,
                         sortInfo: sortInfo,
                         pageSize: pageSize,
                         pageSizes: [25, 50, 75],
                         currentPage: currentPage,
                         totalServerItems: totalServerItems,
                         selectedItem: selectedItem }">
                        </div>
```

So when I initially load my kogrid with data, I want the default sort should be "Salary" "desc".
can you please tell me how to achieve this

**Comment by orneryd** [comment]
use the property 'sortInfo' 

sortInfo: {
            column: 'Salary', //any column name
            direction: 'desc'   // values can be 'asc' or 'desc'
        });

**Comment by suryabg2000** [comment]
Hi,

Can you please help me where should i add the code you mentioned?

Do i need add this n my viewmodel as below

sortInfo: ko.observable({ column: { field: 'Salary' }, direction: "desc" }),

or  
div id="contactsDiv" data-bind="koGrid: { data: searchContacts,
                         columnDefs: [ 
                                        { displayName: 'Name', field: 'Name',  },
                                        { displayName: 'Email', field: 'Email' },
                                        { displayName: 'Phone', field: 'Phone' },
                                        { displayName: 'City', field: 'City' },
                                        { displayName: 'Salary', field: 'Salary' }
                                        ],
                         autogenerateColumns: false,
                         isMultiSelect: true,
                         showFilter: false,
                         enablePaging: true,
                         rowTemplate: 'tmpContactRow', 
                         useExternalFiltering: true,
                         useExternalSorting: true,
                         filterInfo: filterInfo,
                         sortInfo: ({ column: 'Salary', 
                            direction: 'desc'  }),
                         pageSize: pageSize,
                         pageSizes: [25, 50, 75],
                         currentPage: currentPage,
                         totalServerItems: totalServerItems,
                         selectedItem: selectedItem }">
                        </div>
Though I have worked out both the above options it didnot work. so plz help me in this regards

**Comment by orneryd** [comment]
you have parens around the json object in the second part.

sortInfo: ({ column: 'Salary', direction: 'desc' }), 

should be:
sortInfo: { column: 'Salary', direction: 'desc' },

**Comment by suryabg2000** [comment]
when i do this as mentioned below. I am getting error as "Error: TypeError: this.sortInfo.subscribe is not a function". Please look at my triggerattached to my parent view model
sortInfo: { column: 'Salary', direction: 'desc' },

So please help me in this regard

Also I have a viewmodel in which event triggering 
ViewModel.dataChangedTrigger = ko.computed(function () {
sortInfo = MyAnotherViewModel.sortInfo();
});

And another issue is, if i dont want sorting Image Up arrow & down arrow to be visible & as well sorting should not happen on a column . I am setting sortable: false, even this is not working can you help me whats happening

**Comment by chester89** [comment]
I think you need to do: 
sortInfo = MyAnotherViewModel.sortInfo;
There are chances that your sortInfo is not an observable when you do what you mentioned above, therefore subscibe method doesn't work

**Comment by JByfordRew** [comment]
I'm entering sortInfo: { column: 'date', direction: 'desc' } or 'asc' and no change for me, sortInfo does not seem to function.  why do you use 'column' instead of 'field' this seems inconsistent.

**Comment by JByfordRew** [comment]
If anybody has an example of a 'working' sortInfo then please post it up.  Make sure you put the exact code up and don't interchange field or column because I'm still not sure which one to use!  Please post a working example up.  Many thanks.
