### ISSUE TITLE
How to disable sorting for selected columns

### ISSUE THREAD

**Issue by suryabg2000** [Knockout-Contrib/KoGrid#75]
Hi Team,

I have KoGrid defined as follows:

```
                        <div id="outletsDiv" data-bind="koGrid: { data: searchContacts,
                         columnDefs: [ 
                                        { displayName: 'Name', field: 'Name' },
                                        { displayName: 'Title', field: 'UnUsedColumn1' },
                                        { displayName: 'Email', field: 'UnUsedColumn2' },
                                        { displayName: 'Phone', field: 'UnUsedColumn3' },
                                        { displayName: 'City', field: 'UnUsedColumn4' },
                                        { displayName: 'Salary', field: 'Salary' }
                                        ],
                         autogenerateColumns: false,
                         isMultiSelect: true,
                         showFilter: false,
                         enablePaging: true,
                         rowTemplate: 'tmpOutletRow', 
                         useExternalFiltering: true,
                         useExternalSorting: true,
                         filterInfo: filterInfo,
                         sortInfo: sortInfo,
                         pageSize: pageSize,
                         pageSizes: [25, 50, 75],
                         currentPage: currentPage,
                         totalServerItems: totalServerItems,
                         selectedItem: selectedItem }">
                        </div>
```

I want to disable sorting options for columns UnUsedColumn1, UnUsedColumn2, UnUsedColumn3, UnUsedColumn4.

How can I achieve this. Please help me in this regard.

**Comment by orneryd** [comment]
use the column definition variable 'sortable' to accomplish this. such as 
columnDefs: [ 
                                        { displayName: 'Name', field: 'Name' },
                                        { displayName: 'Title', field: 'UnUsedColumn1', sortable: false },
                                        { displayName: 'Email', field: 'UnUsedColumn2', sortable: false  },
                                        { displayName: 'Phone', field: 'UnUsedColumn3', sortable: false },
                                        { displayName: 'City', field: 'UnUsedColumn4', sortable: false  },
                                        { displayName: 'Salary', field: 'Salary',  } ],

**Comment by orneryd** [comment]
you can follow the same pattern for 'resizable' and 'filterable'
