### ISSUE TITLE
Upgrade to KO 2.2 RC

### ISSUE THREAD

**Issue by ericmbarnard** [Knockout-Contrib/KoGrid#78]
KO 2.2 RC is about to be released, so we need to ensure that KoGrid 2.0 is compliant with any changes for that new release

**Comment by orneryd** [comment]
so far what I can tell is that it is compatible with the new RC, we have been using it for a while now. I would refrain from making any code changes unless they are necessary to fix a critical bug. Also, all unit tests pass against the RC 2.2

**Comment by orneryd** [comment]
Closing as we have been running 2.2 knockout for all unit tests and in production.
