### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by ericmbarnard** [Knockout-Contrib/KoGrid#79]
We need to provide a plugin system for KoGrid.

I'm thinking we'd have an api like so:

``` html
<div data-bind="koGrid: { data: myData, plugins: [ 'some-plugin', 'some-other-plugin'] }"></div>
```

We would have a namespace for plugins like `kg.plugins['some-plugin']`

And then finally (and the hard part) we would need to define what the plugin interface would look like. My initial feeling is that it would be something like: 

``` javascript
kg.plugins['some-plugin'] = {
   onGridInit: function(grid) { /* logic */ },
   onGridUpdate: function(grid) { /* logic */ },
   onRowsChanged(grid, rowCollection) { /* logic */ },
   onRowUpdated(grid, row) { /* logic */ },
   onCellUpdated(grid, cell) { /* logic */ }
};
```

Essentially these would all be hooks where we could call the plugin method in the corresponding bindingHandler or so. Something like:

``` javascript
ko.bindingHandlers['koGrid'] = {
    init: function(element, valueAccessor, blah){
    /* snip */
    kg.utils.executeForAllPlugins(grid, 'onGridInit'); 
    }
};
```

Lastly, having a system like this would make it extremely nice for prototyping new features as plugins before pulling them into the KoGrid core.

**Comment by orneryd** [comment]
I copied the way slickgrid handles plugins. But we can expand it to be more robust like you describe. I opened a pull request.
