### ISSUE TITLE
Should have an option for resizable columns

### ISSUE THREAD

**Issue by thelinuxlich** [Knockout-Contrib/KoGrid#8]

**Comment by ericmbarnard** [comment]
@thelinuxlich 

It's in my plans to do this, but perf and just overall correctness have been more of a priority at this point.

**Comment by orneryd** [comment]
I have started working on this. I have moved the width to an observable and out of the css class that gets added.

I am still working on how to actually resize it.

https://github.com/Crash8308/sKoGrid

**Comment by orneryd** [comment]
Resizing is now experimental and works in chrome, firefox, and IE9 with a few quirks.you can check it out on the dev branch of sKoGrid until it gets merged back into koGrid.

**Comment by orneryd** [comment]
Resizing works in IE8 + chrome and firefox on the skogrid-merge branch. adding this to the 1.2 milestone.

**Comment by ericmbarnard** [comment]
@Crash8308 

Is the resizable stuff ready to go? If so go ahead and close this since we'll be merging this branch into master fairly soon.

**Comment by ericmbarnard** [comment]
@Crash8308 just pushed changes to the arrow alignment ... let's play around with this some more before calling it done

**Comment by orneryd** [comment]
Just fixed the sorting arrows CSS file. arrows are now 5px right of the header text in all cases. closing this out
