### ISSUE TITLE
Selection event?

### ISSUE THREAD

**Issue by tdekoekkoek** [Knockout-Contrib/KoGrid#80]
I'm trying to find out how to detect selection and work with the existing selected row.  I also need to be able to hide an id in the grid to use that id when selected.  I do see how to bind to the selected array, but not respond to the event.  Can anyone please explain the selection event to me and also how to hide a column.  Thanks.

**Comment by orneryd** [comment]
So it seems you have two questions here:
1:  "...how to detect selection and work with the existing selected row."
You need to set up the observable for selectedItem and then subscribe to it in your code as follows:
in your viewmodel 
mySelectedObservable = ko.observable(obj)
mySelectedObservable.subscribe(function(){
   //Do Work Here;
})
//then set the selectedItem to the koGrid property
selectedItem: mySelectedObservable;

2."I also need to be able to hide an id in the grid to use that id when selected"

you will need to specify your column definitions following the documentation https://github.com/ericmbarnard/KoGrid/wiki/Defining-Columns

Doing this does not modify your data model. Assuming you do not specify the "Id" property to be displayed in your columnDefs, your Id property will still be in your model but not displayed in the grid.
