### ISSUE TITLE
Header Sort Icons/Arrows Gone in Latest Build

### ISSUE THREAD

**Issue by chimpeenuts** [Knockout-Contrib/KoGrid#84]
Yet another oddity/issue I believe.

Using build: \* Compiled At: 15:27:30.16 Tue 10/02/2012 
seen here: http://jsfiddle.net/PrkR8/2/
notice no icons for sort/order column

Using build: 16:18:10.85 Wed 04/11/2012 
seen here: http://jsfiddle.net/PrkR8/1/
notice ICONS for sort/order column --> yay!

Unless there's a new setting somewhere that I need to enable and I'm missing it something is now getting lost.

NOTE: JSFiddle is exact same code only difference is which KoGrid.js file is linked in.

**Comment by orneryd** [comment]
use the latest CSS from master (there is a bug in jsfiddle, if you copy the CSS from the latest master in the css box it works great.
http://jsfiddle.net/PrkR8/7/
