### ISSUE TITLE
Allow sort on datetime formatted strings

### ISSUE THREAD

**Issue by adam-marshall** [Knockout-Contrib/KoGrid#86]
The sort manager can handle date strings but not datetime sorting, which is dealt with as a standard string. It's a quick win really.

It just needs an additional regex, an extra check at the end of guessSortFn and then an extra sorting function. I have hacked this into the project I am using KoGrid in already, but it would be useful to have this in the next version proper. I am sure others could find a use for this functionality.

**Comment by orneryd** [comment]
You can attach your own sorting function to the column definition with the following syntax in your viewmodel and binding the columDefs to colDefs 
html:

```
<div data-bind="koGrid: { data: myData, columnDefs: colDefs )" ></div>
```

viewModel:

```
myfunc = function(a,b){
        if (a == b) return 0;
        if (a < b) return -1;
        return 1;
};
self.colDefs = 
[{ field: 'item', displayName: 'Item', width: "*",  sortFn: myfunc}]

```

**Comment by adam-marshall** [comment]
Hi, yes I am aware of that I just figured that if it has date string sorting out of the box, then adding datetime sorting to that is relatively straightforward. I've written in those changes locally, was just suggesting that this could be a useful addition?

**Comment by orneryd** [comment]
Totally which is why i haven't closed the issue. this will be in the 2.1 release

**Comment by orneryd** [comment]
fixed in latest commit
