### ISSUE TITLE
Object [object Object] has no method 'getTemplateText'

### ISSUE THREAD

**Issue by davidjsilva** [Knockout-Contrib/KoGrid#91]
There are a couple calls to kg.templateManager.getTemplateText in the new 1.2.1 code and the getTemplateText method is no longer defined.  One in kg.templates.generateRowTemplate when a cell template is defined and the other ko.bindingHandlers['kgRows'].  For me, I noticed it when I got an error when I defined a cell template for a column.

**Comment by davidjsilva** [comment]
Thanks for fixing #91 but it has uncovered another issue.  I'm not sure if calling kg.templateManager.getTemplate is correct here because column cell templates have not been added to the self.templateCache.  Only koGrid, header, header cell, row and footer templates are added to that templateCache object.  Maybe getTemplateFromDom is appropriate here?  In any case what ends up happening is since it can't find that column cell template it returns empty string and then tmpl ends up being undefined and throws an exception when trying to call tmpl.replace.  I've setup this fiddle to show what's happening - http://jsfiddle.net/6FW3j/2/

**Comment by orneryd** [comment]
let me know if the latest commit fixes the issue you are seeing. It should

**Comment by davidjsilva** [comment]
Yes this issue is fixed thanks!  Keep up the great work!
