### ISSUE TITLE
scrolling glitch in IE7

### ISSUE THREAD

**Issue by adam-marshall** [Knockout-Contrib/KoGrid#93]
I know IE7 isn't supported, but I had to support it on a current project utilising kogrid.

There is a scrolling glitch that is reproducable on the kogrid examples. This can be resolved by adding a position:relative; style to kgViewport: 
http://stackoverflow.com/questions/67665/ie7-css-scrolling-div-bug 

This seems to have solved my problem so may be worth adding into the sample css?

**Comment by orneryd** [comment]
I had actually noticed this a long time ago when I was doing something similar. I will go ahead and look into the change, it needs tested in all the other browsers to ensure compatibility.

**Comment by orneryd** [comment]
fixed in latest commit
