### ISSUE TITLE
how to extend KOGRID.js

### ISSUE THREAD

**Issue by suryabg2000** [Knockout-Contrib/KoGrid#98]
Team,

Good Morning,
I have to extend my kogrid as follows
1. add new flag property "showInnerSearch"
which is similar to isMultiSelect & want to use it KOGRID.JS
So to achieve this I have added a property called "showInnerSearch" flag in kg.Defaults
when I added <input type="text" data-bind="visible: kg.showInnerSearch" /> this control right above my kgViewReport this is not working 

can you help me in this. 

Thanks a lot in advance

**Comment by orneryd** [comment]
we are going to be adding a plugin system here in the 2.0 release. then you should be able to extend Kogrid however you see fit in the plugin context.

**Comment by orneryd** [comment]
Also if you want to create a global search control within the grid, this is not something we support directly as we already have a filtering row to allow for searching. I am going to close this in favor of the plugin system issue, examples will be up soon.
